/* Link-only OpenCL symbols. Excluded from the APK. Never executed.
 * Android uses the optional public vendor libOpenCL.so driver. */
void clBuildProgram(void) {}
void clCreateBuffer(void) {}
void clCreateBufferWithProperties(void) {}
void clCreateCommandQueue(void) {}
void clCreateContext(void) {}
void clCreateImage(void) {}
void clCreateKernel(void) {}
void clCreateProgramWithBinary(void) {}
void clCreateProgramWithSource(void) {}
void clCreateSubBuffer(void) {}
void clEnqueueBarrierWithWaitList(void) {}
void clEnqueueCopyBuffer(void) {}
void clEnqueueFillBuffer(void) {}
void clEnqueueMapBuffer(void) {}
void clEnqueueMarkerWithWaitList(void) {}
void clEnqueueNDRangeKernel(void) {}
void clEnqueueReadBuffer(void) {}
void clEnqueueUnmapMemObject(void) {}
void clEnqueueWriteBuffer(void) {}
void clFinish(void) {}
void clFlush(void) {}
void clGetDeviceIDs(void) {}
void clGetDeviceInfo(void) {}
void clGetEventProfilingInfo(void) {}
void clGetKernelInfo(void) {}
void clGetKernelSubGroupInfo(void) {}
void clGetKernelWorkGroupInfo(void) {}
void clGetPlatformIDs(void) {}
void clGetPlatformInfo(void) {}
void clGetProgramBuildInfo(void) {}
void clGetProgramInfo(void) {}
void clReleaseEvent(void) {}
void clReleaseKernel(void) {}
void clReleaseMemObject(void) {}
void clReleaseProgram(void) {}
void clSetKernelArg(void) {}
void clWaitForEvents(void) {}
